# Generated by Django 4.2.8 on 2023-12-18 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("fullname", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=250)),
                ("mobile", models.CharField(max_length=16, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("position", models.CharField(max_length=100)),
                (
                    "id_employee",
                    models.CharField(
                        max_length=6, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
